name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install make (Windows)
      if: runner.os == 'Windows'
      run: choco install -y make mingw

    - name: Install
      run: make install

    - name: Check
      run: make check
